# permissions for end users to edit labelers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: labeler-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pod-distribution-controller
    app.kubernetes.io/part-of: pod-distribution-controller
    app.kubernetes.io/managed-by: kustomize
  name: labeler-editor-role
rules:
- apiGroups:
  - poddistribution.drumato.com
  resources:
  - labelers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - poddistribution.drumato.com
  resources:
  - labelers/status
  verbs:
  - get
