//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDistribution) DeepCopyInto(out *PodDistribution) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDistribution.
func (in *PodDistribution) DeepCopy() *PodDistribution {
	if in == nil {
		return nil
	}
	out := new(PodDistribution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodDistribution) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDistributionList) DeepCopyInto(out *PodDistributionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodDistribution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDistributionList.
func (in *PodDistributionList) DeepCopy() *PodDistributionList {
	if in == nil {
		return nil
	}
	out := new(PodDistributionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodDistributionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDistributionMinAvailableSpec) DeepCopyInto(out *PodDistributionMinAvailableSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDistributionMinAvailableSpec.
func (in *PodDistributionMinAvailableSpec) DeepCopy() *PodDistributionMinAvailableSpec {
	if in == nil {
		return nil
	}
	out := new(PodDistributionMinAvailableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDistributionSelector) DeepCopyInto(out *PodDistributionSelector) {
	*out = *in
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDistributionSelector.
func (in *PodDistributionSelector) DeepCopy() *PodDistributionSelector {
	if in == nil {
		return nil
	}
	out := new(PodDistributionSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDistributionSpec) DeepCopyInto(out *PodDistributionSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(PodDistributionMinAvailableSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDistributionSpec.
func (in *PodDistributionSpec) DeepCopy() *PodDistributionSpec {
	if in == nil {
		return nil
	}
	out := new(PodDistributionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDistributionStatus) DeepCopyInto(out *PodDistributionStatus) {
	*out = *in
	if in.TargetDeployments != nil {
		in, out := &in.TargetDeployments, &out.TargetDeployments
		*out = make([]TargetDeployment, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDistributionStatus.
func (in *PodDistributionStatus) DeepCopy() *PodDistributionStatus {
	if in == nil {
		return nil
	}
	out := new(PodDistributionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetDeployment) DeepCopyInto(out *TargetDeployment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetDeployment.
func (in *TargetDeployment) DeepCopy() *TargetDeployment {
	if in == nil {
		return nil
	}
	out := new(TargetDeployment)
	in.DeepCopyInto(out)
	return out
}
